services:
  - type: web
    name: helpjuice-search
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpjuice_search_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: helpjuice_search_db
    databaseName: helpjuice_search
    user: helpjuice_search 